modLoader="javafml"
loaderVersion="[4,)"
license = 'Unlicense'
issueTrackerURL="https://github.com/Egassy/Tides-of-Time/issues"

[[mods]]
modId="tot"
version="1.0.4"
displayName="Tides of Time" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/tot-addon"
logoFile="tot_logo.png"
credits="The Halcyon and Terrarium teams, for making Halcyon and Tempad respectively"
authors="Egassy"
description="Subsuming Tempad into Data and Essence"

[[dependencies.tot]]
modId="neoforge"
type="required"
versionRange="[21.1.0,]"
ordering="NONE"
side="BOTH"

[[dependencies.tot]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.tot]]
modId="halcyon"
versionRange="[${halcyon_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.tot]]
modId="tempad"
versionRange="[${tempad_version},)"
ordering="AFTER"
side="BOTH"